// js/action.js - わくわくぱんち v0.5
// BGM / 攻撃音 / 撃破音 / 回復アイテム / 丸型画像 / 横向き表記なし
const ActionApp={
  inited:false,running:false,entities:[],effects:[],active:{},cache:{},
  playerKey:'act_player_v05',enemyKey:'act_enemy_v05',bossKey:'act_boss_v05',ngKey:'act_ng_v05',
  audio:null,bgmTimer:null,bgmStep:0,
  init(){if(!this.inited){this.inited=true;this.injectStyle();this.mount();}this.showGame();},
  injectStyle(){if(document.getElementById('act-style-v05'))return;const s=document.createElement('style');s.id='act-style-v05';s.textContent=`
    .action-wrap{flex:1;position:relative;overflow:hidden;background:#8fd3ff}.action-canvas{width:100%;height:100%;display:block;background:linear-gradient(#8fd3ff 0%,#b8efb2 48%,#70c35a 100%)}
    .action-ui{position:absolute;inset:0;pointer-events:none}.action-score,.action-miss{position:absolute;top:6px;background:#0005;color:white;border-radius:14px;padding:5px 9px;font-weight:bold;font-size:13px}.action-score{left:8px}.action-miss{right:8px}
    .action-back,.action-set{position:absolute;bottom:8px;pointer-events:auto;border:none;border-radius:18px;background:#0006;color:white;padding:6px 10px;font-size:12px}.action-back{left:8px}.action-set{right:8px}
    .start-center{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);pointer-events:auto;border:none;border-radius:999px;background:#ff7043;color:white;font-weight:bold;font-size:26px;padding:18px 42px;box-shadow:0 5px 16px #0004}
    .action-settings{display:none;flex:1;overflow-y:auto;padding:12px}.action-settings.active{display:block}.media-card.correct{border-color:#ff7043;background:#fff3e0}
  `;document.head.appendChild(s);},
  mount(){document.getElementById('action').innerHTML=`
    <div id="act-game" class="action-wrap"><canvas id="act-cv" class="action-canvas"></canvas><div class="action-ui">
      <div class="action-score">⭐ <span id="act-score">0</span>　れべる <span id="act-level">1</span></div><div class="action-miss">⚠ <span id="act-miss">0</span>/3</div>
      <button class="action-back" onclick="ActionApp.stop();App.home()">←</button><button class="action-set" onclick="ActionApp.settings()">せってい</button><button id="act-start" class="start-center" onclick="ActionApp.start()">すたーと</button>
    </div></div><div id="act-set" class="action-settings"></div><div id="act-over" class="overlay"><h2>おしまい！</h2><p id="act-result"></p><button class="main" onclick="ActionApp.start()">もういちど</button><button class="sub" onclick="ActionApp.settings()">せってい</button></div>`;
    this.cv=document.getElementById('act-cv');this.ctx=this.cv.getContext('2d');this.resize();window.addEventListener('resize',()=>this.resize());this.bindDrag();},
  resize(){const r=this.cv.getBoundingClientRect(),d=window.devicePixelRatio||1;this.cv.width=Math.max(320,r.width*d);this.cv.height=Math.max(180,r.height*d);this.ctx.setTransform(d,0,0,d,0,0);this.w=r.width;this.h=r.height;},
  showGame(){document.getElementById('act-game').style.display='block';document.getElementById('act-set').classList.remove('active');},
  ids(k){return KidsStorage.ids(k);},setIds(k,a){KidsStorage.setIds(k,a);},media(id){return KidsStorage.get().find(x=>x.id===id);},
  roleList(k,defs){const ids=this.ids(k),a=KidsStorage.get().filter(x=>ids.includes(x.id));return a.length?a:defs;},
  playerData(){return this.media(localStorage.getItem(this.playerKey))||{emoji:'🐼',word:'ぱんだ'};},
  settings(){this.stop();document.getElementById('act-game').style.display='none';const s=document.getElementById('act-set');s.classList.add('active');s.innerHTML=`
    <header class="app-header"><div class="head-line"><button class="back" onclick="ActionApp.showGame()">←</button><h1>👊 ぱんちせってい</h1></div></header><div class="scroll">
    <div class="section"><h3>しゃしんをついか</h3><div class="form"><label class="file">しゃしん<input id="act-file" type="file" accept="image/*"></label><input id="act-word" type="text" placeholder="なまえ"><button id="act-add" class="main">とうろく</button></div></div>
    <div class="section"><h3>しゅじんこう</h3><div id="act-player" class="media"></div></div><div class="section"><h3>てき</h3><div id="act-enemy" class="media"></div></div><div class="section"><h3>ぼす</h3><div id="act-boss" class="media"></div></div><div class="section"><h3>だめなひと</h3><div id="act-ng" class="media"></div></div></div>`;
    document.getElementById('act-add').onclick=async()=>{const f=document.getElementById('act-file').files[0];if(!f){alert('しゃしんをえらんでください');return}await KidsStorage.add(f,document.getElementById('act-word').value.trim()||'しゃしん');this.settings();};this.renderSettings();},
  renderSettings(){this.renderPlayer();this.renderMulti('act-enemy',this.enemyKey);this.renderMulti('act-boss',this.bossKey);this.renderMulti('act-ng',this.ngKey);},
  renderPlayer(){const box=document.getElementById('act-player'),cur=localStorage.getItem(this.playerKey);box.innerHTML='';KidsStorage.get().forEach(m=>{const c=document.createElement('div');c.className='media-card '+(cur===m.id?'correct':'');c.innerHTML=`<img src="${m.image}"><div class="name">${m.word}</div><button class="main">${cur===m.id?'しゅじんこう':'これにする'}</button>`;c.querySelector('button').onclick=()=>{localStorage.setItem(this.playerKey,m.id);this.renderPlayer();};box.appendChild(c);});},
  renderMulti(id,key){const box=document.getElementById(id),ids=this.ids(key);box.innerHTML='';KidsStorage.get().forEach(m=>{const c=document.createElement('div');c.className='media-card '+(ids.includes(m.id)?'selected':'');c.innerHTML=`<img src="${m.image}"><div class="name">${m.word}</div><label><input type="checkbox" ${ids.includes(m.id)?'checked':''}> つかう</label>`;c.querySelector('input').onchange=e=>{let a=this.ids(key);a=e.target.checked?[...a,m.id]:a.filter(x=>x!==m.id);this.setIds(key,a);this.renderMulti(id,key);};box.appendChild(c);});},
  bindDrag(){let drag=false;const pos=e=>{const t=e.touches?e.touches[0]:e,r=this.cv.getBoundingClientRect();return{x:t.clientX-r.left,y:t.clientY-r.top};};const st=e=>{if(!this.player)return;drag=true;this.movePlayer(pos(e));e.preventDefault();};const mv=e=>{if(drag&&this.player){this.movePlayer(pos(e));e.preventDefault();}};const en=()=>drag=false;this.cv.addEventListener('touchstart',st,{passive:false});this.cv.addEventListener('touchmove',mv,{passive:false});this.cv.addEventListener('touchend',en);this.cv.addEventListener('mousedown',st);window.addEventListener('mousemove',mv);window.addEventListener('mouseup',en);},
  movePlayer(p){const dx=p.x-this.player.x,dy=p.y-this.player.y;if(Math.hypot(dx,dy)>2)this.dir=this.norm(dx,dy);this.player.x=Math.max(24,Math.min(this.w-24,p.x));this.player.y=Math.max(24,Math.min(this.h-24,p.y));},
  start(){this.resize();this.ensureAudio();this.running=true;this.score=0;this.miss=0;this.level=1;this.entities=[];this.effects=[];this.lastSpawn=0;this.lastNg=0;this.lastHeal=0;this.lastAttack=0;this.dir={x:1,y:0};this.player={x:this.w/2,y:this.h/2,r:24,data:this.playerData()};document.getElementById('act-start').style.display='none';document.getElementById('act-over').classList.remove('show');this.startBgm();this.loop(performance.now());},
  stop(){this.running=false;this.stopBgm();const s=document.getElementById('act-start');if(s)s.style.display='block';},
  loop(t){if(!this.running)return;this.update(t);this.draw();requestAnimationFrame(tt=>this.loop(tt));},
  update(t){this.level=1+Math.floor(this.score/100);document.getElementById('act-score').textContent=this.score;document.getElementById('act-miss').textContent=this.miss;document.getElementById('act-level').textContent=this.level;if(t-this.lastSpawn>Math.max(450,1100-this.level*90)){this.spawn(Math.random()<0.16&&this.score>=50?'boss':'enemy');this.lastSpawn=t}if(t-this.lastNg>5000){this.spawn('ng');this.lastNg=t}if(t-this.lastHeal>8500){this.spawn('heal');this.lastHeal=t}this.entities.forEach(e=>{e.x+=e.vx;e.y+=e.vy;if(e.type==='ng'&&t-e.birth>5000)e.dead=true;if(e.type==='heal'&&t-e.birth>8000)e.dead=true;});this.collectHeal();this.entities=this.entities.filter(e=>!e.dead&&e.x>-100&&e.y>-100&&e.x<this.w+100&&e.y<this.h+100);if(t-this.lastAttack>170){this.attack();this.lastAttack=t}this.effects.forEach(f=>{f.life--;f.y-=0.8});this.effects=this.effects.filter(f=>f.life>0);},
  spawn(type){if(type==='heal'){this.entities.push({type:'heal',x:40+Math.random()*Math.max(60,this.w-80),y:45+Math.random()*Math.max(60,this.h-90),vx:0,vy:0,r:22,hp:1,max:1,data:{emoji:'🍎'},birth:performance.now()});return}const speed=(1.2+this.level*.18)*(type==='boss'?.7:1),s=this.edge(),target={x:this.w/2+(Math.random()-.5)*this.w*.8,y:this.h/2+(Math.random()-.5)*this.h*.7},v=this.norm(target.x-s.x,target.y-s.y);let data;if(type==='enemy')data=this.pick(this.roleList(this.enemyKey,[{emoji:'🐛'},{emoji:'🐸'},{emoji:'🐱'}]));if(type==='boss')data=this.pick(this.roleList(this.bossKey,[{emoji:'🦁'}]));if(type==='ng')data=this.pick(this.roleList(this.ngKey,[{emoji:'⭐'}]));this.entities.push({type,x:s.x,y:s.y,vx:v.x*speed,vy:v.y*speed,r:type==='boss'?34:26,hp:type==='boss'?5:1,max:type==='boss'?5:1,data,birth:performance.now(),hurt:0});},
  edge(){const s=Math.floor(Math.random()*4);if(s===0)return{x:-40,y:Math.random()*this.h};if(s===1)return{x:this.w+40,y:Math.random()*this.h};if(s===2)return{x:Math.random()*this.w,y:-40};return{x:Math.random()*this.w,y:this.h+40};},
  collectHeal(){for(const e of this.entities){if(e.type!=='heal')continue;if(Math.hypot(e.x-this.player.x,e.y-this.player.y)<45){e.dead=true;if(this.miss>0)this.miss--;this.score+=20;this.fx(e.x,e.y,'かいふく','🍎');this.playHeal();}}},
  attack(){const range=70;for(const e of this.entities){if(e.type==='heal')continue;const dx=e.x-this.player.x,dy=e.y-this.player.y,dist=Math.hypot(dx,dy);if(dist>range+e.r*.35)continue;const n=this.norm(dx,dy),dot=n.x*this.dir.x+n.y*this.dir.y;if(dot<-0.34)continue;if(e.type==='ng'){e.dead=true;this.miss++;this.fx(e.x,e.y,'だめ！','⚠️');this.playNg();if(this.miss>=3)this.gameOver();return}e.hp--;e.hurt=8;this.fx(e.x,e.y,'だめーじ','💥');this.playHit();e.x+=this.dir.x*12;e.y+=this.dir.y*12;if(e.hp<=0){e.dead=true;this.score+=e.type==='boss'?50:10;this.fx(e.x,e.y,e.type==='boss'?'+50':'+10','✨');this.playDefeat();}return;}},
  gameOver(){this.running=false;this.stopBgm();document.getElementById('act-result').textContent=`${this.score} てん！`;document.getElementById('act-over').classList.add('show');document.getElementById('act-start').style.display='block';},
  fx(x,y,text,emoji){this.effects.push({x,y,text,emoji,life:36});},
  draw(){const c=this.ctx,w=this.w,h=this.h;c.clearRect(0,0,w,h);c.fillStyle='rgba(255,255,255,.25)';for(let i=0;i<10;i++){c.beginPath();c.arc((i*97+this.score)%w,30+i%3*25,18,0,Math.PI*2);c.fill()}for(const e of this.entities)this.drawEntity(e);this.drawPlayer();for(const f of this.effects){c.globalAlpha=Math.max(0,f.life/36);c.font='bold 24px sans-serif';c.textAlign='center';c.fillStyle='#fff';c.strokeStyle='#ff7043';c.lineWidth=4;c.strokeText(f.emoji+' '+f.text,f.x,f.y);c.fillText(f.emoji+' '+f.text,f.x,f.y);c.globalAlpha=1;}},
  drawPlayer(){const p=this.player;if(!p)return;this.drawData(p.data,p.x,p.y,p.r);this.ctx.font='30px sans-serif';this.ctx.textAlign='center';this.ctx.fillText('👊',p.x+this.dir.x*34,p.y+this.dir.y*34+10);},
  drawEntity(e){this.drawData(e.data,e.x,e.y,e.r,e.hurt);if(e.type==='boss'){this.ctx.fillStyle='#0006';this.ctx.fillRect(e.x-e.r,e.y-e.r-12,e.r*2,6);this.ctx.fillStyle='#ff7043';this.ctx.fillRect(e.x-e.r,e.y-e.r-12,e.r*2*(e.hp/e.max),6);}},
  drawData(d,x,y,r,hurt=0){const c=this.ctx;c.save();c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.clip();if(d.image){const img=this.img(d.image);if(img.complete)c.drawImage(img,x-r,y-r,r*2,r*2);else{c.fillStyle='#fff';c.fillRect(x-r,y-r,r*2,r*2)}}else{c.fillStyle='#fff';c.fillRect(x-r,y-r,r*2,r*2);c.font=(r*1.55)+'px sans-serif';c.textAlign='center';c.textBaseline='middle';c.fillText(d.emoji||'🐼',x,y)}if(hurt>0){c.fillStyle='rgba(255,0,0,.28)';c.fillRect(x-r,y-r,r*2,r*2)}c.restore();c.strokeStyle='#fff';c.lineWidth=3;c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.stroke();},
  img(src){if(!this.cache[src]){const i=new Image();i.src=src;this.cache[src]=i}return this.cache[src]},pick(a){return a[Math.floor(Math.random()*a.length)]},norm(x,y){const l=Math.hypot(x,y)||1;return{x:x/l,y:y/l}},
  ensureAudio(){if(!this.audio)this.audio=new(window.AudioContext||window.webkitAudioContext)();if(this.audio.state==='suspended')this.audio.resume();},
  tone(f,d=0.12,type='sine',vol=0.12){this.ensureAudio();const o=this.audio.createOscillator(),g=this.audio.createGain();o.connect(g);g.connect(this.audio.destination);o.frequency.value=f;o.type=type;g.gain.setValueAtTime(vol,this.audio.currentTime);g.gain.exponentialRampToValueAtTime(0.001,this.audio.currentTime+d);o.start();o.stop(this.audio.currentTime+d);},
  playHit(){this.tone(180,0.09,'square',0.10)},playDefeat(){this.tone(660,0.08,'triangle',0.12);setTimeout(()=>this.tone(880,0.12,'triangle',0.10),70)},playNg(){this.tone(90,0.25,'sawtooth',0.14)},playHeal(){this.tone(523,0.08,'sine',0.10);setTimeout(()=>this.tone(784,0.12,'sine',0.10),80)},
  startBgm(){this.stopBgm();const notes=[262,330,392,330,294,349,440,349];this.bgmStep=0;this.bgmTimer=setInterval(()=>{if(this.running){this.tone(notes[this.bgmStep%notes.length],0.20,'triangle',0.035);this.bgmStep++;}},280)},stopBgm(){clearInterval(this.bgmTimer);this.bgmTimer=null;}
};