const HiraganaApp={
  inited:false,items:[],current:null,dummy:true,clearCount:0,medals:0,
  init(){if(!this.inited){this.inited=true;this.load();this.mount()}this.showHome()},
  defaultItems(){return[{id:'init_zou',word:'ぞう',emoji:'🐘',cleared:false},{id:'init_ari',word:'あり',emoji:'🐜',cleared:false}]},
  load(){try{this.items=JSON.parse(localStorage.getItem('hiragana_items_v02')||'null')||this.defaultItems()}catch(e){this.items=this.defaultItems()}this.clearCount=Number(localStorage.getItem('hiragana_clear_count_v02')||0);this.medals=Number(localStorage.getItem('hiragana_medals_v02')||0);this.dummy=localStorage.getItem('hiragana_dummy_v02')!=='false'},
  save(){localStorage.setItem('hiragana_items_v02',JSON.stringify(this.items));localStorage.setItem('hiragana_clear_count_v02',this.clearCount);localStorage.setItem('hiragana_medals_v02',this.medals);localStorage.setItem('hiragana_dummy_v02',this.dummy)},
  mount(){document.getElementById('hiragana-screen').innerHTML=`<header class="app-header"><div class="top-line"><button class="back-btn" onclick="App.home()">←</button><h1>🐘 ひらがなぱずる</h1></div><div class="small-info">えをえらんでね　🏅 <span id="hiragana-medal">0</span></div></header><div id="hiragana-home"><div class="content-scroll"><div class="toolbar"><button class="main-btn" onclick="HiraganaApp.showSettings()">しゃしんをたす</button><label><input type="checkbox" id="dummyCheck"> よけいなもじ</label></div><div id="hiragana-list" class="card-grid"></div></div></div><div id="hiragana-play"><div id="hiragana-image"></div><div id="slots"></div><div id="letters"></div><div style="padding:8px;text-align:center"><button class="sub-btn" onclick="HiraganaApp.showHome()">もどる</button><button class="main-btn" onclick="HiraganaApp.startItem(HiraganaApp.current)">もういちど</button></div></div><div id="hiragana-settings"><div class="content-scroll"><div class="section"><h3>しゃしんをついか</h3><div class="form"><label class="file-label">しゃしん<input type="file" id="hiraPhoto" accept="image/*"></label><input id="hiraWord" type="text" placeholder="こたえ　れい：いぬ"><button class="main-btn" id="hiraAddBtn">とうろく</button><button class="sub-btn" onclick="HiraganaApp.showHome()">もどる</button></div></div><div class="section"><h3>ほぞんしゃしんからつくる</h3><p class="tiny">なまえをいれて、このえをひらがなぱずるにいれます。</p><div id="hiraMedia" class="media-list"></div></div></div></div>`;document.getElementById('dummyCheck').checked=this.dummy;document.getElementById('dummyCheck').onchange=e=>{this.dummy=e.target.checked;this.save()};document.getElementById('hiraAddBtn').onclick=()=>this.addPhotoItem()},
  show(el){['hiragana-home','hiragana-play','hiragana-settings'].forEach(id=>document.getElementById(id).classList.remove('active'));document.getElementById(el).classList.add('active')},showHome(){this.show('hiragana-home');this.renderList()},showSettings(){this.show('hiragana-settings');this.renderMediaChoices()},
  renderList(){document.getElementById('hiragana-medal').textContent=this.medals;const list=document.getElementById('hiragana-list');list.innerHTML='';this.items.forEach(item=>{const card=document.createElement('button');card.className='item-card';card.onclick=()=>this.startItem(item);if(item.image){card.innerHTML=`<img src="${item.image}"><div class="item-label">${item.word}</div>${item.cleared?'<div class="check">✓</div>':''}`}else{const c=document.createElement('canvas');c.width=160;c.height=160;const ctx=c.getContext('2d');ctx.fillStyle='#fff8e1';ctx.fillRect(0,0,160,160);ctx.font='92px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(item.emoji,80,84);card.appendChild(c);card.insertAdjacentHTML('beforeend',`<div class="item-label">${item.word}</div>${item.cleared?'<div class="check">✓</div>':''}`)}list.appendChild(card)})},
  renderMediaChoices(){KidsStorage.renderMediaList(document.getElementById('hiraMedia'),{mode:'addHiragana',allowDelete:true,onAdd:(item,word)=>{word=(word||item.word||'').trim();if(!word){alert('なまえをいれてください');return}this.items.push({id:'hira_'+Date.now(),word,image:item.image,cleared:false});KidsStorage.updateMediaWord(item.id,word);this.save();this.showHome()},onDelete:()=>this.showSettings()})},
  startItem(item){this.current=item;this.show('hiragana-play');const img=document.getElementById('hiragana-image');img.innerHTML=item.image?`<img src="${item.image}">`:item.emoji;const slots=document.getElementById('slots');slots.innerHTML='';Array.from(item.word).forEach((ch,i)=>{const s=document.createElement('div');s.className='slot';s.dataset.index=i;slots.appendChild(s)});this.renderLetters()},
  renderLetters(){const letters=document.getElementById('letters');letters.innerHTML='';let arr=Array.from(this.current.word);if(this.dummy){const kana='あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわん';while(arr.length<Math.min(this.current.word.length+3,8))arr.push(kana[Math.floor(Math.random()*kana.length)])}KidsStorage.shuffle(arr);arr.forEach(ch=>{const d=document.createElement('div');d.className='letter';d.textContent=ch;d.dataset.ch=ch;this.addLetterDrag(d);letters.appendChild(d)})},
  addLetterDrag(el){let clone=null;const size=52;const xy=e=>e.touches?{x:e.touches[0].clientX,y:e.touches[0].clientY}:{x:e.clientX,y:e.clientY};const pos=(x,y)=>{clone.style.left=(x-size/2)+'px';clone.style.top=(y-size/2)+'px'};const start=e=>{e.preventDefault();KidsStorage.speak(el.dataset.ch);const p=xy(e);clone=el.cloneNode(true);clone.style.cssText=`position:fixed;z-index:999;width:${size}px;height:${size}px;pointer-events:none;opacity:.92`;pos(p.x,p.y);document.body.appendChild(clone)};const move=e=>{if(!clone)return;e.preventDefault();const p=xy(e);pos(p.x,p.y)};const end=e=>{if(!clone)return;e.preventDefault();clone.remove();clone=null;const p=e.changedTouches?{x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY}:{x:e.clientX,y:e.clientY};const empty=[...document.querySelectorAll('.slot')].filter(s=>!s.textContent);let target=null;for(const s of empty){const r=s.getBoundingClientRect();if(p.x>=r.left&&p.x<=r.right&&p.y>=r.top&&p.y<=r.bottom){target=s;break}}if(target){target.textContent=el.dataset.ch;target.onclick=()=>{target.textContent='';el.style.visibility='visible'};el.style.visibility='hidden';this.check()}};el.addEventListener('touchstart',start,{passive:false});el.addEventListener('touchmove',move,{passive:false});el.addEventListener('touchend',end,{passive:false});el.addEventListener('mousedown',start);document.addEventListener('mousemove',move);document.addEventListener('mouseup',end)},
  check(){const s=[...document.querySelectorAll('.slot')].map(x=>x.textContent).join('');if(s.length!==this.current.word.length)return;if(s===this.current.word)this.correct();else{KidsStorage.speak('おしい');setTimeout(()=>{document.querySelectorAll('.slot').forEach(x=>x.textContent='');document.querySelectorAll('.letter').forEach(x=>x.style.visibility='visible')},500)}},
  correct(){KidsStorage.speak(this.current.word);const d=document.createElement('div');d.className='sparkle';d.textContent='✨ できた！ ✨';document.body.appendChild(d);setTimeout(()=>d.remove(),950);if(!this.current.cleared){this.current.cleared=true;this.clearCount++;if(this.clearCount%10===0){this.medals++;setTimeout(()=>{const m=document.createElement('div');m.className='sparkle';m.textContent='🏅 めだる！';document.body.appendChild(m);KidsStorage.speak('めだる');setTimeout(()=>m.remove(),950)},700)}}this.save();setTimeout(()=>this.showHome(),1200)},
  async addPhotoItem(){const file=document.getElementById('hiraPhoto').files[0];let word=document.getElementById('hiraWord').value.trim().replace(/\s/g,'');if(!file||!word){alert('しゃしんとこたえをいれてください');return}word=word.replace(/[ァ-ン]/g,ch=>String.fromCharCode(ch.charCodeAt(0)-0x60));const item=await KidsStorage.addMediaFromFile(file,word);this.items.push({id:'hira_'+Date.now(),word,image:item.image,cleared:false});this.save();document.getElementById('hiraPhoto').value='';document.getElementById('hiraWord').value='';this.showHome()}
};
